### PR TITLE
Playlist area

### PR DESCRIPTION
**Pull request by JuanChavezHuerta**
Pushing about page html & css

### CODE REVIEW

**Comment by jkeopangna** [comment]
Cool

**Comment by jkeopangna** [comment]
Cool

**Comment by jkeopangna** [comment]
Cool

**Comment by jkeopangna** [comment]
so cool

**Comment by jkeopangna** [comment]
very cool

**Comment by jkeopangna** [comment]
This looks good

**Review by langjeff — APPROVED** [review]

**Pull request merged**
